final class BZip2DecompressionState {
	byte[] a;
	int b;
	int c;
	int d;
	int e;
	byte[] f;
	int g;
	int h;
	int i;
	int j;
	byte k;
	int l;
	boolean m;
	int n;
	int o;
	int p;
	int q;
	int r;
	int s;
	int t;
	final int[] u = new int[256];
	int v;
	final int[] w = new int[257];
	public static int[] x;
	int y;
	final boolean[] z = new boolean[256];
	final boolean[] A = new boolean[16];
	final byte[] B = new byte[256];
	final byte[] C = new byte[4096];
	final int[] D = new int[16];
	final byte[] E = new byte[18002];
	final byte[] F = new byte[18002];
	final byte[][] G = new byte[6][258];
	final int[][] H = new int[6][258];
	final int[][] I = new int[6][258];
	final int[][] J = new int[6][258];
	final int[] K = new int[6];
	int L;
}
